### PR TITLE
fix update-release-branch.sh, links for v8 website

### LINKED ISSUE #2497: [Bug] examples link to 7.0-release
### Description

The examples on https://visgl.github.io/react-map-gl/examples currently link to the 7.0-release branch. It would be helpful to update them to point to the 8.0-release branch instead.

I took a quick peek at `scripts/update-release-branch.sh`, and it appears to be outdated. For example, it tries to update .js files rather than .ts and .tsx files, and it seems to depend on the old repository structure (before the introduction of the mapbox and maplibre subdirectories). I also tried running it on Linux with `dash`, and it seems there are some macOS/Bash-specific assumptions as well.

Should we update this script, or is there a more appropriate approach for handling this task in the current setup?

### Expected Behavior

The examples on the site should link to the 8.0-release branch.

### Steps to Reproduce

1. Navigate to https://visgl.github.io/react-map-gl/examples
2. Click any of the example links
3. Click the View Code in the example
4. Note that `https://github.com/visgl/react-map-gl/tree/7.0-release/examples/<example>` is opened

### Environment

This will happen in any browser.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by geneukum**
The `update-release-branch.sh` script was not updating `.ts` and `.tsx` files and was relying on an old repo structure. Let's make the script work with the new structure and then update links in the docs and examples, replacing outdated versions (e.g., `7.0-release`, `react-mapbox-gl`) with the correct v8 links.

This fixes #2497.

### CODE REVIEW

File: scripts/update-release-branch.sh [hunk 1]
```diff
@@ -10,19 +10,18 @@ VERSION=`echo "$1.0"`
 echo "Updating branch to ${BRANCH}..."
 
 # Replace source links in docs and examples
-find docs -iname "*.md" -type f -exec sed -i '' -E "s/react-map-gl\/(tree|blob)\/(master|[0-9\.]+-release)/react-map-gl\/tree\/${BRANCH}/g" {} \;
-find examples -maxdepth 0 -iname "*.md" -type f -exec sed -i '' -E "s/react-map-gl\/(tree|blob)\/(master|[0-9\.]+-release)/react-map-gl\/tree\/${BRANCH}/g" {} \;
-find examples/*/src -iname "*.js" -type f -exec sed -i '' -E "s/react-map-gl\/(tree|blob)\/(master|[0-9\.]+-release)/react-map-gl\/tree\/${BRANCH}/g" {} \;
+find docs -mindepth 2 -iname "*.md" -exec perl -i -pe "s/react-map-gl\/(tree|blob)\/(master|[0-9\.]+-release)/react-map-gl\/tree\/${BRANCH}/g" {} \;
```
Comment (geneukum) [inline scripts/update-release-branch.sh:13]: I'm not super confident in adding `-mindepth 2` here. The reason that I added it is that there are a few markdown files under /docs (README.md, upgrade-guide.md, and whats-new.md) that seem to be manually maintained. I’d definitely appreciate any additional thoughts on this.

**Comment by Pessimistress** [comment]
Greatly appreciate your find! I guess the issue came from rearranging the docs directory from v7 to v8...

**Review by Pessimistress — APPROVED** [review]
